language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
  - composer self-update --snapshot
  - composer update $COMPOSER_OPTS

script:
  - ./vendor/bin/phpunit
  - ./tests/lint.sh

git:
  depth: 5
