language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  - LARAVEL_VERSION=""
  - LARAVEL_VERSION="5.1"
  - LARAVEL_VERSION="5.2"
  - LARAVEL_VERSION="5.3"
  - LARAVEL_VERSION="5.4"

install:
  - composer self-update --snapshot
  - travis/laravel.php
  - composer update

script:
  - ./vendor/bin/phpunit
  - ./tests/lint.sh

git:
  depth: 5

dist: trusty
sudo: false
